spring:
  application:
    name: scheduler
---
spring:
  profiles.active: default
---
spring:
  profiles: default,dev,ci,qa,production
  # Datasource Configuration
spring.datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${SCHEDULER_DB_HOST:localhost}:${SCHEDULER_DB_PORT:5432}/${SCHEDULER_DB_NAME:postgres}?currentSchema=public"
    username: ${SCHEDULER_DB_USER:postgres}
    password: ${SCHEDULER_DB_PASSWORD:}
spring.jpa:
        # Specify the DBMS
        database: PostgreSQL
        # Show or not log for each sql query
        show-sql: false
        # Hibernate settings are prefixed with spring.jpa.hibernate.*
        hibernate:
            ddl-auto: create-drop # validate | update | create | create-drop
            dialect: org.hibernate.dialect.PostgreSQLDialect
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
            show_sql: false
            format_sql: true
---
# Dkron configurations
dkron:
    server:
     baseUri: http://${DKRON_HOST:localhost}:${DKRON_PORT:8080}/v1
     
server:
    port: "${SERVER_PORT:8090}"
     
