#spring:
#  profiles.active: test
---
spring:
  profiles: development
spring.jpa:
    show-sql: true
    hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        ddl-auto: create-drop 
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scheduler
    username: root
    password: passw0rd
    # Keep the connection alive if idle for a long time (needed in production)#
    testWhileIdle: true  
---
#This profile include in memory database configuration and disable flyway
spring:
  profiles: test
spring.datasource: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:MY_APP;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:db/migration/test/init_tests.sql';
    username: sa
    password:
spring.jpa:
    hibernate:
        ddl-auto: update 
        dialect: org.hibernate.dialect.PostgreSQLDialect
flyway.enabled : false
#flyway.schemas : PUBLIC
---
